Discussion: Rm custom __getattr__ method?
Cadasta/django-jsonattrs pull request #30
Opened 2018-01-08 20:14 UTC by alukach

## Background

I've been working towards optimizing API endpoints in the Cadasta/cadasta-platform project.  When looking at the `parties` endpoint, I see a high number of queries when serializing a relatively small number of resources.

![screen shot 2018-01-08 at 11 58 04 am](https://user-images.githubusercontent.com/897290/34688759-6b01645e-f470-11e7-8911-9ae797064c9e.png)

It seems that in the process of the Django REST Framework serializing each resource into JSON, it casts the resource's `attributes` value to a `dict`.  I believe that Python's `dict` class initialization internally works something like this:

```py
self = {}
for key in input_data:
    self[key] = input_data[key]
```

Thus, we run `__getattr__` on the `JSONAttributes` field.  This runs `self.setup_from_dict` so that it may run `self._check_key(key)`. `setup_from_dict` runs `validate` on every element in its data, requiring a lookup the `attr_type` foreign key:

https://github.com/Cadasta/django-jsonattrs/blob/4f06cdea8dbe131aa78e1ac1b67cd9837d9ad038/jsonattrs/fields.py#L27-L36
https://github.com/Cadasta/django-jsonattrs/blob/4f06cdea8dbe131aa78e1ac1b67cd9837d9ad038/jsonattrs/models.py#L294-L304

Thus, we're running 1 SQL query for every attribute of every resource being returned in the API. In the case of the API example above, the API is returning 10 resources that each have 3 attributes resulting in 30 separate queries.  Being that the API returns 100 resources by default and that resources often have more than 3 attributes, it's clear that this can quickly become a performance issue.

## Change

The simplest fix for this would be to remove the `__getattr__` customization for the `JSONAttributes` object.  **I'm not really sure what the purpose of running `self._check_key(key)` on reads from the object, so please let me know if this is a bad idea.**  Running validation on writes seems necessary, but I think we could get away from running it on reads.

After this change, our API problems went away:

![screen shot 2018-01-08 at 11 57 11 am](https://user-images.githubusercontent.com/897290/34690294-c78865d8-f475-11e7-8bad-dfd413fed494.png)

2018-01-19 07:57 UTC, seav requested changes
The description of the PR is good. I understand why the changes were made.

But given that this change in behavior did not fail any tests, I think we need to add a unit test or two to confirm whatever it is `__getitem__` is supposed to be doing.

2018-01-19 15:58 UTC, alukach commented
Reading over this, it looks like I was saying `__getattr__` when I meant `__getitem__`.  It seems like @seav was able to look past this.

> I think we need to add a unit test or two to confirm whatever it is __getitem__ is supposed to be doing.

 @seav I'm not quite following what you mean by this.  If we do as suggested in this PR and remove the customized `__getitem__` method, we'll be using the default.  This feels like it would be unnecessary to test.  I suppose the test would look something like:

```py
def test_getitem(self):
    x = {'a': 1}
    assert x.__getitem__('a') == x['a'] == 1

    with self.assertRaises(KeyError):
        x['b']
```

Again, this feels unnecessary.

2018-01-30 13:02 UTC, oliverroick requested changes
I agree that a test for non-custom code is not necessary. 

While the changes look ok, they seem to make a functional test fail. Can you have a look to see what's going on?

2018-02-15 21:31 UTC, alukach commented
@seav @oliverroick Alright, I think we're good to go.  See Cadasta/cadasta-platform#1984 for passing functional test.

2018-02-16 00:56 UTC, seav commented
@alukach: It seems a unit test is failing on Cadasta/cadasta-platform#1984. Is this related to the work that Oliver did in a different PR?

2018-02-16 04:09 UTC, alukach commented
@seav Resolved. https://github.com/Cadasta/cadasta-platform/pull/1984/commits/d0f68bbab7926a3bb88e26c41c662b458d21e72c#r168672071

2018-02-16 09:14 UTC, oliverroick approved these changes

2018-02-16 09:23 UTC, seav approved these changes

2018-02-16 14:57 UTC, merged