Loosen Django's required version
Cadasta/django-jsonattrs pull request #34
Opened 2018-02-13 00:03 UTC by alukach

I don't believe we should fix the required version of Django for a library.  Instead, we should specify a minimum version.  Currently, every time I install `django-jsonattrs`, it uninstalls my currently-installed version of Django and installs the version specified in `setup.py`.  It should be up to the consumer of this library to ensure that their version of Django is up to date on security concerns, this module is only in charge of reporting which versions of Django support this module's functionality.

2018-02-13 06:30 UTC, seav approved these changes

2018-02-13 13:21 UTC, oliverroick requested changes

2018-02-13 13:21 UTC, oliverroick commented on setup.py
> +        'Django>=1.9',
Should we at least narrow the required Django version to the ones we support, i.e. `Django>=1.11,<2.1`?

2018-02-13 14:53 UTC, alukach commented on setup.py
> +        'Django>=1.9',
Sure, we can do that. I had reverted it back to the earliest version supported by the lib.

2018-02-16 07:57 UTC, oliverroick approved these changes

2018-02-16 08:08 UTC, merged